version: '3'
services: 
  jenkins:
    # image: jenkins/jenkins:2.60.3-alpine
    build: ./jenkins
    container_name: jenkins
    ports: 
      - "50000:50000"
      - "8080:8080"
    volumes: 
      - ./data/jenkins/home:/var/jenkins_home
      - ./data/jenkins/log:/var/log/jenkins
      - ./data/jenkins/cache:/var/cache/jenkins
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
      - DOCKER_HOST=unix:///var/run/docker.sock
    # prepare:
    command: sudo mkdir opt
    restart: always